[build]
builder = "dockerfile"

[deploy]
startCommand = "python manage.py migrate && gunicorn pss_backend.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"