# Render Blueprint for PSS Backend
# This file can be used to set up the service on Render

services:
  - type: web
    name: pss-backend
    env: python
    runtime: python-3.11.9
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    plan: starter # Change to 'standard' or 'pro' for production

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true # Render will generate a secure key
      - key: ALLOWED_HOSTS
        value: "*" # Will be updated with actual domain
      - key: CORS_ALLOWED_ORIGINS
        value: "https://pss-frontend-ebon.vercel.app/" # Update with your frontend

      # Database will be auto-connected if you add PostgreSQL service
      - key: DB_SSL
        value: true

      # Security settings for production
      - key: SECURE_SSL_REDIRECT
        value: true
      - key: CSRF_COOKIE_SECURE
        value: true
      - key: SESSION_COOKIE_SECURE
        value: true
      - key: SECURE_HSTS_SECONDS
        value: 31536000
      - key: SECURE_HSTS_INCLUDE_SUBDOMAINS
        value: true
      - key: SECURE_HSTS_PRELOAD
        value: true

      # Optional: Auto-create superuser on first deploy
      # - key: DJANGO_SUPERUSER_EMAIL
      #   value: admin@capaciti.org.za
      # - key: DJANGO_SUPERUSER_PASSWORD
      #   generateValue: true

databases:
  - name: pss-database
    databaseName: pss_database
    user: pss_user
    plan: starter # Change to 'standard' or 'pro' for production