# Generated by Django 4.2.7 on 2025-11-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_timestamps_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('candidate', 'Candidate'), ('admin', 'Admin'), ('superuser', 'Superuser')], default='candidate', max_length=20),
        ),
    ]
