# Generated by Django 4.2.7 on 2025-11-30 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_encrypt_existing_pii_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Full privacy policy text')),
                ('effective_date', models.DateTimeField(help_text='When this version becomes effective')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False, help_text='Only one version should be active at a time')),
            ],
            options={
                'verbose_name': 'Privacy Policy Version',
                'verbose_name_plural': 'Privacy Policy Versions',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('data_processing', 'General Data Processing'), ('medical_data', 'Medical Data Processing'), ('communications', 'Marketing Communications'), ('data_sharing', 'Data Sharing with Partners')], max_length=50)),
                ('granted', models.BooleanField(default=False, help_text='Whether consent was granted (True) or withdrawn (False)')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address when consent was granted (for audit trail)', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent when consent was granted')),
                ('privacy_policy_version', models.ForeignKey(help_text='Which privacy policy version user consented to', on_delete=django.db.models.deletion.PROTECT, to='users.privacypolicyversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Consent',
                'verbose_name_plural': 'User Consents',
                'ordering': ['-granted_at'],
            },
        ),
        migrations.CreateModel(
            name='DataExportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, help_text='Path to exported data file (if stored)', max_length=500)),
                ('download_count', models.IntegerField(default=0, help_text='Number of times the export was downloaded')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the export file expires (24-48 hours typical)', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Export Request',
                'verbose_name_plural': 'Data Export Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='DataDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True, help_text="User's reason for requesting deletion (optional)")),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes about the deletion decision')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_proof', models.TextField(blank=True, help_text='Record of what data was deleted (for compliance proof)')),
                ('retention_until', models.DateTimeField(blank=True, help_text='Date until which this deletion record must be retained', null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_deletion_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User requesting data deletion', on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Deletion Request',
                'verbose_name_plural': 'Data Deletion Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
