# Generated by Django 4.2.7 on 2025-12-01 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_privacypolicyversion_userconsent_dataexportrequest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_deletion_date', models.DateTimeField(help_text='Date when account will be permanently deleted')),
                ('first_warning_sent', models.DateTimeField(blank=True, null=True)),
                ('second_warning_sent', models.DateTimeField(blank=True, null=True)),
                ('exempted', models.BooleanField(default=False, help_text='If True, account is exempt from automatic deletion (admin override)')),
                ('exemption_reason', models.TextField(blank=True, help_text='Reason for exemption from automatic deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_schedule', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_deletion_date'],
                'indexes': [models.Index(fields=['scheduled_deletion_date', 'exempted'], name='users_accou_schedul_0f1f41_idx')],
            },
        ),
    ]
