# Generated by Django 4.2.7 on 2025-12-01 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_privacypolicyversion_userconsent_dataexportrequest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
    ]
