# Generated by Django 4.2.7 on 2025-12-02 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_account_deletion_schedule'),
        ('users', '0007_remove_redundant_date_of_birth'),
    ]

    operations = [
    ]
