# Generated by Django 4.2.7 on 2025-12-29 12:26

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_password_policy_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totp_enabled',
            field=models.BooleanField(default=False, help_text='Whether 2FA is enabled for this user'),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_enabled_at',
            field=models.DateTimeField(blank=True, help_text='When 2FA was enabled', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_last_used',
            field=models.DateTimeField(blank=True, help_text='Last successful 2FA verification', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Encrypted TOTP secret (base32)', null=True),
        ),
    ]
