# Generated by Django 4.2.26 on 2025-12-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_password_policy_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='accountdeletionschedule',
            name='users_accou_schedul_0f1f41_idx',
        ),
        migrations.AlterField(
            model_name='accountdeletionschedule',
            name='exempted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accountdeletionschedule',
            name='exemption_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='accountdeletionschedule',
            name='scheduled_deletion_date',
            field=models.DateTimeField(),
        ),
    ]
