# Generated by Django 4.2.7 on 2025-12-29 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0002_usersession'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorBackupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(db_index=True, help_text='SHA256 hash of backup code', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this code was generated')),
                ('used', models.BooleanField(default=False, help_text='Whether this code has been used')),
                ('used_at', models.DateTimeField(blank=True, help_text='When this code was used', null=True)),
                ('user', models.ForeignKey(help_text='User who owns this backup code', on_delete=django.db.models.deletion.CASCADE, related_name='backup_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'used'], name='authenticat_user_id_490aac_idx')],
            },
        ),
    ]
